#!/bin/bash
# 遍历所有传入参数

current_dir="$(pwd)"

cd $current_dir/

for arg in "$@"; do
    vcs_url=$(apt-cache showsrc "$arg" 2>/dev/null | grep '^Vcs-Git:' | awk '{print $2}')
    if [ -n "$vcs_url" ]; then
        echo "有Git，那就先 git clone $vcs_url ...."
        git clone "$vcs_url" "$arg-src" || {
            echo "git clone $vcs_url 失败了，还是先下载压缩包吧..."
            apt-get source --download-only "$arg"
        }
    else
        echo "没有Git，直接下载压缩包 ...."
        apt-get source --download-only "$arg"
    fi
done
