#!/bin/bash
cd $(pwd)/
git submodule update --init --recursive --force
git submodule update --init --recursive --force
git submodule update --init --recursive --force
git submodule update --init --recursive --force
git submodule update --init --recursive --force
git submodule update --init --recursive --force
git submodule update --init --recursive --force
git submodule update --init --recursive --force
git submodule update --init --recursive --force
git submodule update --init --recursive --force

mkdir build_dir_for_build
cd build_dir_for_build
